# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venAviso(object):
    def setupUi(self, venAviso):
        venAviso.setObjectName("venAviso")
        venAviso.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(venAviso)
        self.buttonBox.setGeometry(QtCore.QRect(60, 220, 289, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(venAviso)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 91, 81))
        self.label_2.setMinimumSize(QtCore.QSize(50, 71))
        self.label_2.setMaximumSize(QtCore.QSize(11111111, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/icono_aviso.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lblAvisoSalir = QtWidgets.QLabel(venAviso)
        self.lblAvisoSalir.setGeometry(QtCore.QRect(30, 110, 351, 100))
        self.lblAvisoSalir.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lblAvisoSalir.setFont(font)
        self.lblAvisoSalir.setText("")
        self.lblAvisoSalir.setScaledContents(True)
        self.lblAvisoSalir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAvisoSalir.setObjectName("lblAvisoSalir")

        self.retranslateUi(venAviso)
        QtCore.QMetaObject.connectSlotsByName(venAviso)

    def retranslateUi(self, venAviso):
        _translate = QtCore.QCoreApplication.translate
        venAviso.setWindowTitle(_translate("venAviso", "Dialog"))
