# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAbout.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venAbout(object):
    def setupUi(self, venAbout):
        venAbout.setObjectName("venAbout")
        venAbout.resize(400, 300)
        venAbout.setStyleSheet("background-color: rgb(255, 255, 239);")
        self.btnBoxCerrar = QtWidgets.QDialogButtonBox(venAbout)
        self.btnBoxCerrar.setGeometry(QtCore.QRect(150, 220, 81, 32))
        self.btnBoxCerrar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnBoxCerrar.setOrientation(QtCore.Qt.Horizontal)
        self.btnBoxCerrar.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.btnBoxCerrar.setObjectName("btnBoxCerrar")
        self.layoutWidget = QtWidgets.QWidget(venAbout)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 130, 204, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(venAbout)
        self.label_3.setGeometry(QtCore.QRect(150, 30, 101, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(venAbout)
        self.btnBoxCerrar.accepted.connect(venAbout.accept)
        self.btnBoxCerrar.rejected.connect(venAbout.reject)
        QtCore.QMetaObject.connectSlotsByName(venAbout)

    def retranslateUi(self, venAbout):
        _translate = QtCore.QCoreApplication.translate
        venAbout.setWindowTitle(_translate("venAbout", "Dialog"))
        self.label.setText(_translate("venAbout", "Versión del programa 0.0.1"))
        self.label_2.setText(_translate("venAbout", "Alberto Portas Pérez"))
